In [193]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine

In [194]:
dataset=load_wine()
x=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [195]:
x

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [196]:
y=pd.DataFrame(dataset.target,columns=['target'])

In [197]:
y

target
0         0
1         0
2         0
3         0
4         0
..      ...
173       2
174       2
175       2
176       2
177       2

[178 rows x 1 columns]

In [198]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [199]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [200]:
x_train

array([[ 1.65449169, -0.58917969,  1.21899459, ..., -1.69987192,
        -0.92046835, -0.27671104],
       [-0.5813379 ,  2.84887015,  0.99967413, ..., -0.60303724,
        -1.30182791, -0.73846263],
       [-0.77898029, -1.13675421, -0.97420996, ...,  0.36217728,
         0.22361033, -0.27671104],
       ...,
       [ 1.70390229, -0.4186237 ,  0.0492855 , ...,  1.06415147,
         0.54847218,  2.54793491],
       [-0.38369551, -0.72382916, -0.38935541, ...,  0.01119018,
        -0.77922407, -0.8021525 ],
       [-0.81603824,  0.10202093,  0.34171277, ..., -0.69078402,
         1.08520045, -0.98366865]])

In [201]:
x_test

array([[ 7.89806212e-01,  6.85501974e-01,  7.07246859e-01,
        -1.28970717e+00,  1.14155847e+00,  6.48764240e-01,
         1.00469996e+00, -1.54592178e+00,  1.21070982e-01,
         1.81290590e-02,  1.11901785e-02,  1.05695159e+00,
         3.12420304e-01],
       [ 1.49390724e+00,  1.52930533e+00,  2.68605950e-01,
        -1.78652700e-01,  7.90491768e-01,  8.89113972e-01,
         6.23192602e-01, -4.98406993e-01, -5.97283511e-01,
         7.86888566e-02, -3.83670306e-01,  1.01457831e+00,
         1.06077633e+00],
       [-8.72319135e-02,  4.25179662e-01,  1.21899459e+00,
         4.51945783e-01, -2.62708342e-01, -1.20994036e+00,
        -1.53533585e+00,  1.35488840e+00, -1.47332558e+00,
        -1.98155932e-01, -8.22404177e-01, -4.26113366e-01,
        -4.67780662e-01],
       [ 9.00980058e-01, -7.50759059e-01,  1.21899459e+00,
         9.02373272e-01,  8.83583612e-02,  1.12946370e+00,
         1.22557264e+00, -5.78985054e-01,  1.38257156e+00,
         2.77671049e-01,  1.02027808e

In [202]:
y_train

target
158       2
137       2
98        1
159       2
38        0
..      ...
71        1
106       1
14        0
92        1
102       1

[142 rows x 1 columns]

In [203]:
y_test

target
19        0
45        0
140       2
30        0
67        1
16        0
119       1
174       2
109       1
141       2
24        0
150       2
41        0
118       1
15        0
111       1
113       1
82        1
9         0
114       1
18        0
66        1
60        1
169       2
171       2
164       2
117       1
65        1
90        1
55        0
29        0
128       1
145       2
31        0
12        0
42        0

In [204]:
from sklearn.neighbors import KNeighborsClassifier

In [205]:
knn=KNeighborsClassifier(n_neighbors=5,weights='uniform',metric='euclidean')

In [207]:
y_train_1D=y_train.values.ravel()
knn.fit(x_train,y_train_1D)

KNeighborsClassifier(metric='euclidean')

In [210]:
y_pred=knn.predict(x_test)

In [211]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [212]:
print(accuracy_score(y_test,y_pred))

0.9444444444444444


In [215]:
print(confusion_matrix(y_test,y_pred))

[[14  0  0]
 [ 1 12  1]
 [ 0  0  8]]


In [216]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      1.00      0.97        14
           1       1.00      0.86      0.92        14
           2       0.89      1.00      0.94         8

    accuracy                           0.94        36
   macro avg       0.94      0.95      0.94        36
weighted avg       0.95      0.94      0.94        36

